security:
  api:
    key: ${API_SECRET_KEY}
    enabled: true
    header-name: "X-API-KEY"
  
  rate-limit:
    enabled: ${RATE_LIMIT_ENABLED:true}
    user-requests-per-minute: ${RATE_LIMIT_USER_REQUESTS_PER_MINUTE:10}
    api-requests-per-minute: ${RATE_LIMIT_API_REQUESTS_PER_MINUTE:100}
    cleanup-interval: 60000 # 1 minute
  
  validation:
    enabled: true
    max-message-length: 4096
    max-callback-data-length: 64
    allowed-callback-prefixes:
      - "buy_stars"
      - "show_prices"
      - "help"
      - "my_orders"
      - "back_to_main"
      - "select_package_"
      - "confirm_order_"
      - "cancel_order"
      - "pay_ton_"
      - "pay_crypto_"
      - "check_payment_"
  
  audit:
    enabled: ${SECURITY_AUDIT_ENABLED:true}
    log-level: ${SECURITY_LOG_LEVEL:INFO}
    log-sensitive-data: false
  
  cors:
    enabled: true
    allowed-origins:
      - "http://localhost:3000"
      - "http://localhost:8080"
    allowed-methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
    allowed-headers:
      - "Content-Type"
      - "Authorization"
      - "X-API-KEY"
    max-age: 3600

redis:
  host: localhost
  port: 6379
  timeout: 2000ms
  database: 0
  lettuce:
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0

logging:
  level:
    shit.back.security: ${SECURITY_LOG_LEVEL:INFO}
    org.springframework.security: WARN
